### ISSUE TITLE
Fatal error: Uncaught Error after updating to the latest Radio Station dev relaase

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/newspack-platform#31]
Probably not a bug since I uploaded the lastest dev release https://github.com/OpenProducer/newspack-platform/tree/radio/wp-content/plugins/radio-station

Which is probably not compatible with this version of PRO 
https://github.com/OpenProducer/newspack-platform/tree/radio/wp-content/plugins/radio-station-pro-premium

You can see the error on the Pantheon environment - both of you are already set up as users if you wanna root around
https://radio-newspack.pantheonsite.io/
https://radio-newspack.pantheonsite.io/wp-admin/

Not a huge deal since we're not providing this branch to any customers (yet).

**Comment by tonyzeoli** [comment]
Yes, it's not compatible with Premium yet. Please do not install Premium at this time. Roll back to just PRO.

**Comment by gusaus** [comment]
I don't even know what Premium is - I just downloaded and committed/pushed https://github.com/netmix/radio-station/tree/develop but didn't touch pro. Again, not a big deal at the moment since nobody is using or testing this branch (aside from me/us).

I would like to get on the same page with the dev flow next week. Ideally, we can bring in some additional folks looking to gain experience by contributing to open source projects like WordPress.

**Comment by majick777** [comment]
@gusaus I just retested Radio Station develop (2.4.9.9) with Pro premium 2.4.1.10 and didn't get an error. Can you provide us with the exact error you get when you are reporting? It will save time having to login places to find the information you are already seeing. To save time I'd rather only login to test something if I can't see what the problem is already from the provided error message, as that's usually enough to go on.

@gusaus @tonyzeoli The difference between "premium" is that it is an "upgrade" in the Freemius system, whereas without the "(Premium)" in the plugin header, it is treated as an addon instead. They usee different licenses and the license used needs to match. We moved from Pro as an "addon" to Pro as an "upgrade", but going forward we are going to use bundles instead, so technically it will move back to an "addon". _Except_ that we can only provide a free trial for an "upgrade", so fortunately we can do both as we support both (though it was a real pain to get that working!

**Comment by gusaus** [comment]
Closing out as this error has gone away after removing Radio Station PRO from this repo.
